import type { TickerCategory } from '@/domain/types';

export const POPULAR_TICKERS_DISPLAY_COUNT = 6;

export const TICKER_CATEGORIES: readonly TickerCategory[] = [
    {
        id: 'megacap',
        label: '메가캡·지수',
        tickers: [
            'AAPL',
            'MSFT',
            'NVDA',
            'GOOGL',
            'AMZN',
            'META',
            'TSLA',
            'SPY',
            'QQQ',
        ],
    },
    {
        id: 'ai-semiconductor',
        label: 'AI·반도체',
        tickers: ['AMD', 'AVGO', 'ARM', 'SMCI', 'ALAB', 'SOUN'],
    },
    {
        id: 'software-cloud',
        label: '소프트웨어·클라우드',
        tickers: ['PLTR', 'CRWD', 'SNOW', 'NOW', 'CRM', 'DDOG', 'NET'],
    },
    {
        id: 'fintech-crypto',
        label: '핀테크·크립토',
        tickers: ['COIN', 'MSTR', 'HOOD', 'SQ', 'PYPL', 'SOFI', 'AFRM'],
    },
    {
        id: 'leveraged-etf',
        label: '레버리지 ETF',
        tickers: ['TQQQ', 'SQQQ', 'SOXL', 'TSLL', 'NVDL'],
    },
    {
        id: 'healthcare-bio',
        label: '헬스케어·바이오',
        tickers: ['LLY', 'NVO', 'UNH', 'ISRG', 'AMGN'],
    },
];

export const POPULAR_TICKERS = [
    // --- [1] Mega Cap & Index ---
    'AAPL',
    'MSFT',
    'NVDA',
    'GOOGL',
    'AMZN',
    'META',
    'TSLA',
    'NFLX',
    'BRK.B',
    'SPY',
    'QQQ',
    'IWM',
    'VTI',
    'DIA',

    // --- [2] Semi / AI / Infra ---
    'AMD',
    'INTC',
    'AVGO',
    'QCOM',
    'TXN',
    'MU',
    'ASML',
    'LRCX',
    'AMAT',
    'KLAC',
    'SMCI',
    'ARM',
    'MRVL',
    'VRT',
    'ALAB',
    'ASTS',
    'SOUN',
    'BBAI',
    'AI',

    // --- [3] Quantum Computing ---
    'BTQ',
    'IONQ',
    'RGTI',
    'QBTS',
    'QUBT',
    'LAES',
    'IBM',

    // --- [4] Software / SaaS / Cloud ---
    'CRM',
    'NOW',
    'ADBE',
    'ORCL',
    'SNOW',
    'PLTR',
    'PANW',
    'CRWD',
    'ZS',
    'DDOG',
    'MDB',
    'NET',
    'SHOP',
    'DOCU',
    'ZM',
    'TEAM',
    'PATH',
    'U',
    'RBLX',

    // --- [5] Fintech / Crypto / Meme ---
    'COIN',
    'MSTR',
    'MARA',
    'RIOT',
    'CLSK',
    'WULF',
    'HOOD',
    'SQ',
    'PYPL',
    'SOFI',
    'AFRM',
    'UPST',
    'NU',
    'GME',
    'AMC',
    'RDDT',
    'DJT',
    'CVNA',
    'DKNG',

    // --- [6] EV / Mobility / Space ---
    'RIVN',
    'NIO',
    'LCID',
    'XPEV',
    'LI',
    'F',
    'GM',
    'STLA',
    'UBER',
    'LYFT',
    'ABNB',
    'BKNG',
    'LUNR',
    'SPCE',

    // --- [7] Leveraged ETFs ---
    'TQQQ',
    'SQQQ',
    'SOXL',
    'SOXS',
    'TSLL',
    'NVDL',
    'LABU',

    // --- [8] Big Financials ---
    'JPM',
    'BAC',
    'WFC',
    'C',
    'GS',
    'MS',
    'SCHW',
    'BLK',
    'V',
    'MA',
    'AXP',

    // --- [9] Consumer / Retail / Food ---
    'COST',
    'WMT',
    'TGT',
    'HD',
    'LOW',
    'NKE',
    'SBUX',
    'MCD',
    'DIS',
    'KO',
    'PEP',
    'PG',
    'LULU',

    // --- [10] Energy / Industrials / Materials ---
    'XOM',
    'CVX',
    'OXY',
    'SLB',
    'COP',
    'EOG',
    'CAT',
    'DE',
    'GE',
    'BA',
    'HON',
    'UPS',
    'FDX',

    // --- [11] Healthcare / Pharma / Bio ---
    'LLY',
    'NVO',
    'UNH',
    'JNJ',
    'PFE',
    'MRK',
    'ABBV',
    'TMO',
    'DHR',
    'ISRG',
    'AMGN',
    'GILD',

    // --- [12] China ADR / Global ---
    'BABA',
    'JD',
    'PDD',
    'BIDU',
    'TCEHY',
    'TSM',
    'SPOT',
    'PINS',
    'SNAP',
    'ETSY',
] as const;
