// 이 파일은 생성물이다. 직접 고치지 않는다.
// 재생성: yarn guide:links  (scripts/generate-guide-links.ts)
// 원천: skills/**/*.md frontmatter(name, pattern, gating.triggers) + db/seeds/guide/*/*/ko.md(category, skills)

/** 스킬 frontmatter `name` → 가이드 경로. */
export const GUIDE_PATH_BY_SKILL_NAME: Readonly<Record<string, string>> = {
    'Doji Pattern Guide': '/guide/candlesticks/doji',
    'Marubozu Guide': '/guide/candlesticks/marubozu',
    'Hammer/Shooting Star Guide': '/guide/candlesticks/hammer-shooting-star',
    'Counterattack / Belt Hold Guide':
        '/guide/candlesticks/counterattack-belt-hold',
    'Bullish Engulfing Guide': '/guide/candlesticks/bullish-engulfing',
    'Bearish Engulfing Guide': '/guide/candlesticks/bearish-engulfing',
    'Harami Pattern Guide': '/guide/candlesticks/harami',
    'Piercing Line / Dark Cloud Cover Guide':
        '/guide/candlesticks/piercing-dark-cloud',
    'Tweezers Pattern Guide': '/guide/candlesticks/tweezers',
    'Morning/Evening Star Guide': '/guide/candlesticks/morning-evening-star',
    'Abandoned Baby / Tri-Star Guide':
        '/guide/candlesticks/abandoned-baby-tri-star',
    'Three Soldiers/Crows Guide': '/guide/candlesticks/three-soldiers-crows',
    'Three Inside / Outside Guide': '/guide/candlesticks/three-inside-outside',
    'Three-Line Strike Guide': '/guide/candlesticks/three-line-strike',
    'Rising/Falling Three Methods Guide': '/guide/candlesticks/three-methods',
    'Advance Block / Ladder Bottom Guide':
        '/guide/candlesticks/advance-block-ladder-bottom',
    'Above/Below the Stomach Guide': '/guide/candlesticks/stomach',
    'Gap Continuation Guide (Tasuki / Neck)':
        '/guide/candlesticks/gap-continuation',
    'Upside Gap Two Crows / Downside Gap Two Rabbits Guide':
        '/guide/candlesticks/gap-two-crows-rabbits',
    이중바닥: '/guide/chart-patterns/double-bottom',
    이중천장: '/guide/chart-patterns/double-top',
    헤드앤숄더: '/guide/chart-patterns/head-and-shoulders',
    역헤드앤숄더: '/guide/chart-patterns/inverse-head-and-shoulders',
    삼중바닥: '/guide/chart-patterns/triple-bottom',
    삼중천장: '/guide/chart-patterns/triple-top',
    상승삼각형: '/guide/chart-patterns/ascending-triangle',
    하락삼각형: '/guide/chart-patterns/descending-triangle',
    대칭삼각형: '/guide/chart-patterns/symmetrical-triangle',
    상승쐐기: '/guide/chart-patterns/ascending-wedge',
    하락쐐기: '/guide/chart-patterns/descending-wedge',
    상승깃발: '/guide/chart-patterns/bull-flag',
    하락깃발: '/guide/chart-patterns/bear-flag',
    페넌트: '/guide/chart-patterns/pennant',
    '하이 타이트 플래그': '/guide/chart-patterns/high-tight-flag',
    직사각형: '/guide/chart-patterns/rectangle',
    '상승 채널': '/guide/chart-patterns/ascending-channel',
    '하락 채널': '/guide/chart-patterns/descending-channel',
    '확장형 패턴(브로드닝)': '/guide/chart-patterns/broadening-formation',
    컵앤핸들: '/guide/chart-patterns/cup-and-handle',
    원형바닥: '/guide/chart-patterns/rounding-bottom',
    원형천장: '/guide/chart-patterns/rounding-top',
    'ADX Signal Guide': '/guide/indicators/adx',
    'ATR Signal Guide': '/guide/indicators/atr',
    'Bollinger Bands Signal Guide': '/guide/indicators/bollinger-bands',
    'Bollinger %B & BandWidth Signal Guide':
        '/guide/indicators/bollinger-percent-b',
    'Buy/Sell Volume Signal Guide': '/guide/indicators/buy-sell-volume',
    'CCI Signal Guide': '/guide/indicators/cci',
    'Chandelier Exit Signal Guide': '/guide/indicators/chandelier-exit',
    'CMF Signal Guide': '/guide/indicators/cmf',
    'Connors RSI Signal Guide': '/guide/indicators/connors-rsi',
    'DMI Signal Guide': '/guide/indicators/dmi',
    'Donchian Channel Signal Guide': '/guide/indicators/donchian-channel',
    'Elder Impulse System Signal Guide': '/guide/indicators/elder-impulse',
    'Elder-Ray Signal Guide': '/guide/indicators/elder-ray',
    'EMA Signal Guide': '/guide/indicators/ema',
    'EWMA Volatility Signal Guide': '/guide/indicators/ewma-volatility',
    'Force Index Signal Guide': '/guide/indicators/force-index',
    'Hurst Exponent Signal Guide': '/guide/indicators/hurst',
    'Ichimoku Cloud Signal Guide': '/guide/indicators/ichimoku-cloud',
    'Keltner Channel Signal Guide': '/guide/indicators/keltner-channel',
    'MA Signal Guide': '/guide/indicators/ma',
    'MACD-V Signal Guide': '/guide/indicators/macd-v',
    'MACD Signal Guide': '/guide/indicators/macd',
    'MFI Signal Guide': '/guide/indicators/mfi',
    'OBV Signal Guide': '/guide/indicators/obv',
    'Parabolic SAR Signal Guide': '/guide/indicators/parabolic-sar',
    'Regression R-Squared Signal Guide': '/guide/indicators/regression-r2',
    'RSI Signal Guide': '/guide/indicators/rsi',
    '스마트 머니 컨셉 (SMC)': '/guide/indicators/smart-money-concepts',
    '스퀴즈 모멘텀 신호 가이드': '/guide/indicators/squeeze-momentum',
    'Stochastic RSI Signal Guide': '/guide/indicators/stochastic-rsi',
    'Stochastic Signal Guide': '/guide/indicators/stochastic',
    'Supertrend Signal Guide': '/guide/indicators/supertrend',
    'Variance Ratio Signal Guide': '/guide/indicators/variance-ratio',
    'Volume Profile Signal Guide': '/guide/indicators/volume-profile',
    'VWAP Signal Guide': '/guide/indicators/vwap',
    'Williams %R Signal Guide': '/guide/indicators/williams-r',
    'Yang-Zhang Volatility Signal Guide': '/guide/indicators/yang-zhang',
    '엘리어트 파동': '/guide/strategies/elliott-wave',
    '피보나치 전략': '/guide/strategies/fibonacci',
    '다이버전스 전략': '/guide/strategies/divergence',
    '브레이크아웃 전략': '/guide/strategies/breakout',
    '이동평균선 대순환 분석': '/guide/strategies/ma-cycle',
    'MACD 대순환 분석': '/guide/strategies/macd-cycle',
    '평균 회귀 전략': '/guide/strategies/mean-reversion',
    '갭 분석': '/guide/strategies/gap-analysis',
    '52주 신고가 모멘텀': '/guide/strategies/52-week-high-momentum',
    '다중 시간대 분석': '/guide/strategies/multi-timeframe',
    '피봇 포인트': '/guide/strategies/pivot-points',
};

/** 탐지 id(`pattern`·`gating.triggers`) → 가이드 경로. 겹치면 카테고리 순서상 먼저 쓴 쪽이 이긴다. */
export const GUIDE_PATH_BY_TRIGGER: Readonly<Record<string, string>> = {
    doji: '/guide/candlesticks/doji',
    gravestone_doji: '/guide/candlesticks/doji',
    dragonfly_doji: '/guide/candlesticks/doji',
    spinning_top: '/guide/candlesticks/doji',
    bullish_marubozu: '/guide/candlesticks/marubozu',
    bearish_marubozu: '/guide/candlesticks/marubozu',
    hammer: '/guide/candlesticks/hammer-shooting-star',
    inverted_hammer: '/guide/candlesticks/hammer-shooting-star',
    shooting_star: '/guide/candlesticks/hammer-shooting-star',
    hanging_man: '/guide/candlesticks/hammer-shooting-star',
    bullish_counterattack_line: '/guide/candlesticks/counterattack-belt-hold',
    bearish_counterattack_line: '/guide/candlesticks/counterattack-belt-hold',
    bullish_belt_hold: '/guide/candlesticks/counterattack-belt-hold',
    bearish_belt_hold: '/guide/candlesticks/counterattack-belt-hold',
    bullish_engulfing: '/guide/candlesticks/bullish-engulfing',
    bearish_engulfing: '/guide/candlesticks/bearish-engulfing',
    bullish_harami: '/guide/candlesticks/harami',
    bearish_harami: '/guide/candlesticks/harami',
    bullish_harami_cross: '/guide/candlesticks/harami',
    bearish_harami_cross: '/guide/candlesticks/harami',
    piercing_line: '/guide/candlesticks/piercing-dark-cloud',
    dark_cloud_cover: '/guide/candlesticks/piercing-dark-cloud',
    tweezers_top: '/guide/candlesticks/tweezers',
    tweezers_bottom: '/guide/candlesticks/tweezers',
    morning_star: '/guide/candlesticks/morning-evening-star',
    evening_star: '/guide/candlesticks/morning-evening-star',
    morning_doji_star: '/guide/candlesticks/morning-evening-star',
    evening_doji_star: '/guide/candlesticks/morning-evening-star',
    bullish_abandoned_baby: '/guide/candlesticks/abandoned-baby-tri-star',
    bearish_abandoned_baby: '/guide/candlesticks/abandoned-baby-tri-star',
    bullish_triple_star: '/guide/candlesticks/abandoned-baby-tri-star',
    bearish_triple_star: '/guide/candlesticks/abandoned-baby-tri-star',
    three_white_soldiers: '/guide/candlesticks/three-soldiers-crows',
    three_black_crows: '/guide/candlesticks/three-soldiers-crows',
    three_inside_up: '/guide/candlesticks/three-inside-outside',
    three_inside_down: '/guide/candlesticks/three-inside-outside',
    three_outside_up: '/guide/candlesticks/three-inside-outside',
    three_outside_down: '/guide/candlesticks/three-inside-outside',
    bullish_three_line_strike: '/guide/candlesticks/three-line-strike',
    bearish_three_line_strike: '/guide/candlesticks/three-line-strike',
    rising_three_methods: '/guide/candlesticks/three-methods',
    falling_three_methods: '/guide/candlesticks/three-methods',
    advance_block: '/guide/candlesticks/advance-block-ladder-bottom',
    ladder_bottom: '/guide/candlesticks/advance-block-ladder-bottom',
    above_the_stomach: '/guide/candlesticks/stomach',
    below_the_stomach: '/guide/candlesticks/stomach',
    upside_gap_tasuki: '/guide/candlesticks/gap-continuation',
    downside_gap_tasuki: '/guide/candlesticks/gap-continuation',
    on_neck: '/guide/candlesticks/gap-continuation',
    in_neck: '/guide/candlesticks/gap-continuation',
    upside_gap_two_crows: '/guide/candlesticks/gap-two-crows-rabbits',
    downside_gap_two_rabbits: '/guide/candlesticks/gap-two-crows-rabbits',
    double_bottom: '/guide/chart-patterns/double-bottom',
    double_top: '/guide/chart-patterns/double-top',
    head_and_shoulders: '/guide/chart-patterns/head-and-shoulders',
    inverse_head_and_shoulders:
        '/guide/chart-patterns/inverse-head-and-shoulders',
    triple_bottom: '/guide/chart-patterns/triple-bottom',
    triple_top: '/guide/chart-patterns/triple-top',
    ascending_triangle: '/guide/chart-patterns/ascending-triangle',
    descending_triangle: '/guide/chart-patterns/descending-triangle',
    symmetrical_triangle: '/guide/chart-patterns/symmetrical-triangle',
    ascending_wedge: '/guide/chart-patterns/ascending-wedge',
    descending_wedge: '/guide/chart-patterns/descending-wedge',
    bull_flag: '/guide/chart-patterns/bull-flag',
    bear_flag: '/guide/chart-patterns/bear-flag',
    pennant: '/guide/chart-patterns/pennant',
    high_tight_flag: '/guide/chart-patterns/high-tight-flag',
    rectangle: '/guide/chart-patterns/rectangle',
    ascending_channel: '/guide/chart-patterns/ascending-channel',
    descending_channel: '/guide/chart-patterns/descending-channel',
    broadening_formation: '/guide/chart-patterns/broadening-formation',
    cup_and_handle: '/guide/chart-patterns/cup-and-handle',
    rounding_bottom: '/guide/chart-patterns/rounding-bottom',
    rounding_top: '/guide/chart-patterns/rounding-top',
    bollinger_percentb_oversold: '/guide/indicators/bollinger-percent-b',
    bollinger_percentb_overbought: '/guide/indicators/bollinger-percent-b',
    cci_bullish_cross: '/guide/indicators/cci',
    cci_bearish_cross: '/guide/indicators/cci',
    cmf_bullish_flip: '/guide/indicators/cmf',
    cmf_bearish_flip: '/guide/indicators/cmf',
    dmi_bullish_cross: '/guide/indicators/dmi',
    dmi_bearish_cross: '/guide/indicators/dmi',
    ichimoku_cloud_breakout: '/guide/indicators/ichimoku-cloud',
    ichimoku_cloud_breakdown: '/guide/indicators/ichimoku-cloud',
    macd_bullish_cross: '/guide/indicators/macd',
    macd_bearish_cross: '/guide/indicators/macd',
    macd_histogram_bullish_convergence: '/guide/indicators/macd',
    macd_histogram_bearish_convergence: '/guide/indicators/macd',
    mfi_oversold_bounce: '/guide/indicators/mfi',
    mfi_overbought_reversal: '/guide/indicators/mfi',
    parabolic_sar_flip: '/guide/indicators/parabolic-sar',
    parabolic_sar_bearish_flip: '/guide/indicators/parabolic-sar',
    rsi_oversold: '/guide/indicators/rsi',
    rsi_overbought: '/guide/indicators/rsi',
    rsi_bullish_divergence: '/guide/indicators/rsi',
    rsi_bearish_divergence: '/guide/indicators/rsi',
    squeeze_momentum_bullish: '/guide/indicators/squeeze-momentum',
    squeeze_momentum_bearish: '/guide/indicators/squeeze-momentum',
    supertrend_bullish_flip: '/guide/indicators/supertrend',
    supertrend_bearish_flip: '/guide/indicators/supertrend',
    bollinger_upper_breakout: '/guide/strategies/breakout',
    keltner_upper_breakout: '/guide/strategies/breakout',
    keltner_lower_breakout: '/guide/strategies/breakout',
    golden_cross: '/guide/strategies/ma-cycle',
    death_cross: '/guide/strategies/ma-cycle',
    gap_up: '/guide/strategies/gap-analysis',
    gap_down: '/guide/strategies/gap-analysis',
    new_52w_high: '/guide/strategies/52-week-high-momentum',
    new_52w_low: '/guide/strategies/52-week-high-momentum',
};
