import {
    collectPopularOptionsTickers,
    createYahooOptionsProbe,
    deduplicatePopularTickerEntries,
    renderPopularOptionsTickersFile,
    visitKrRejection,
    visitUsRejection,
    writePopularTickerArtifacts,
} from '../../../../update-popular-tickers';

describe('createYahooOptionsProbe', () => {
    it('uses the Yahoo alias before probing options', async () => {
        const options = vi.fn().mockResolvedValue({
            expirationDates: [new Date('2026-06-19T00:00:00.000Z')],
        });
        const probe = createYahooOptionsProbe({ options });

        await expect(probe('BRK.B')).resolves.toBe(true);
        expect(options).toHaveBeenCalledWith('BRK-B', undefined, {
            validateResult: false,
        });
    });
});

describe('deduplicatePopularTickerEntries', () => {
    it('POPULAR_TICKERS 배열에서 첫 등장 티커만 유지한다', () => {
        const fileContent = `export const POPULAR_TICKERS = [
    // --- [1] Mega Cap & Index ---
    'AAPL',
    'BRK.B',
    'PBR-A',

    // --- Trending (2026-04-12) ---
    'T',
    'PBR-A',

    // --- Trending (2026-05-11) ---
    'T',
    'BRK.B',
    'NVDA',
] as const;
`;

        const result = deduplicatePopularTickerEntries(fileContent);

        expect(result.removedTickers).toEqual(['PBR-A', 'T', 'BRK.B']);
        expect(result.content).toBe(`export const POPULAR_TICKERS = [
    // --- [1] Mega Cap & Index ---
    'AAPL',
    'BRK.B',
    'PBR-A',

    // --- Trending (2026-04-12) ---
    'T',

    // --- Trending (2026-05-11) ---
    'NVDA',
] as const;
`);
    });

    it('POPULAR_TICKERS 밖의 같은 티커는 중복 제거 대상으로 보지 않는다', () => {
        const fileContent = `export const TICKER_CATEGORIES = [
    {
        id: 'ev-mobility',
        tickers: ['TSLA'],
    },
];

export const POPULAR_TICKERS = [
    'TSLA',
    'NVDA',
    'TSLA',
] as const;
`;

        const result = deduplicatePopularTickerEntries(fileContent);

        expect(result.removedTickers).toEqual(['TSLA']);
        expect(result.content).toContain("tickers: ['TSLA']");
        expect(result.content).toContain(`export const POPULAR_TICKERS = [
    'TSLA',
    'NVDA',
] as const;`);
    });

    it('POPULAR_TICKERS 배열을 찾지 못하면 원문을 그대로 반환한다', () => {
        const fileContent = `export const OTHER_TICKERS = ['AAPL', 'AAPL'];`;

        expect(deduplicatePopularTickerEntries(fileContent)).toEqual({
            content: fileContent,
            removedTickers: [],
        });
    });
});

describe('collectPopularOptionsTickers', () => {
    it('returns uppercase, deduplicated, sorted option tickers in chunks of 5', async () => {
        let activeProbes = 0;
        let maxActiveProbes = 0;
        const probe = vi.fn(
            async (_symbol: string) =>
                new Promise<boolean>(resolve => {
                    activeProbes += 1;
                    maxActiveProbes = Math.max(maxActiveProbes, activeProbes);
                    setTimeout(() => {
                        activeProbes -= 1;
                        resolve(true);
                    }, 0);
                })
        );

        await expect(
            collectPopularOptionsTickers(
                ['msft', 'AAPL', 'googl', 'tsla', 'nvda', 'amzn', 'msft'],
                probe
            )
        ).resolves.toEqual(['AAPL', 'AMZN', 'GOOGL', 'MSFT', 'NVDA', 'TSLA']);

        expect(maxActiveProbes).toBeLessThanOrEqual(5);
        expect(probe).toHaveBeenCalledTimes(6);
        expect(probe.mock.calls.map(([symbol]) => symbol)).toEqual([
            'AAPL',
            'AMZN',
            'GOOGL',
            'MSFT',
            'NVDA',
            'TSLA',
        ]);
    });

    it('treats a resolved false as a valid no-options result', async () => {
        const probe = vi.fn().mockResolvedValue(false);

        await expect(
            collectPopularOptionsTickers(['NOOPT'], probe)
        ).resolves.toEqual([]);
    });

    it('rejects the whole refresh when one probe fails', async () => {
        const probe = vi.fn(async (symbol: string) => {
            if (symbol === 'FAIL') throw new Error('Yahoo unavailable');
            return true;
        });

        await expect(
            collectPopularOptionsTickers(['AAPL', 'FAIL'], probe)
        ).rejects.toThrow('Yahoo unavailable');
    });
});

describe('renderPopularOptionsTickersFile', () => {
    it('renders a generated readonly literal array', () => {
        expect(renderPopularOptionsTickersFile(['AAPL', 'MSFT'])).toBe(
            `// Generated by update-popular-tickers.ts. Do not edit manually.
export const POPULAR_OPTIONS_TICKERS = [
    'AAPL',
    'MSFT',
] as const;
`
        );
    });
});

describe('writePopularTickerArtifacts', () => {
    it('probes every ticker before writing the popular and options files', async () => {
        const writers = {
            writeAll: vi.fn(),
        };
        const probe = vi
            .fn()
            .mockImplementation(async (symbol: string) => symbol !== 'NOOPT');

        await writePopularTickerArtifacts(
            'popular content',
            ['msft', 'AAPL', 'NOOPT'],
            probe,
            writers
        );

        expect(probe).toHaveBeenCalledWith('AAPL');
        expect(probe).toHaveBeenCalledWith('MSFT');
        expect(probe).toHaveBeenCalledWith('NOOPT');
        expect(writers.writeAll).toHaveBeenCalledWith(
            'popular content',
            `// Generated by update-popular-tickers.ts. Do not edit manually.
export const POPULAR_OPTIONS_TICKERS = [
    'AAPL',
    'MSFT',
] as const;
`
        );
    });

    it('does not invoke either writer when any Yahoo probe fails', async () => {
        const writers = {
            writeAll: vi.fn(),
        };
        const probe = vi.fn().mockRejectedValue(new Error('Yahoo unavailable'));

        await expect(
            writePopularTickerArtifacts(
                'popular content',
                ['AAPL'],
                probe,
                writers
            )
        ).rejects.toThrow('Yahoo unavailable');

        expect(writers.writeAll).not.toHaveBeenCalled();
    });
});

describe('visitUsRejection', () => {
    const ok = {
        symbol: 'PLTR',
        price: 30,
        marketCap: 60_000_000_000,
        isEtf: false,
        isFund: false,
        isActivelyTrading: true,
        exchange: 'NASDAQ',
        companyName: 'Palantir',
    };

    it('조건을 모두 만족하면 null', () => {
        expect(visitUsRejection(ok, 5, false)).toBeNull();
    });

    it.each([
        ['프로필 없음', null, 5, false, 'no FMP profile'],
        [
            '거래 중단',
            { ...ok, isActivelyTrading: false },
            5,
            false,
            'not actively trading',
        ],
        [
            '크립토 거래소',
            { ...ok, exchange: 'CRYPTO' },
            5,
            false,
            'exchange CRYPTO',
        ],
        ['OTC', { ...ok, exchange: 'OTC' }, 5, false, 'exchange OTC'],
        ['펀드', { ...ok, isFund: true }, 5, false, 'fund'],
        [
            'ETF(플래그 없음)',
            { ...ok, isEtf: true },
            5,
            false,
            'ETF (pass --include-etf)',
        ],
        ['저가', { ...ok, price: 4.99 }, 5, false, 'price < $5'],
        [
            '소형',
            { ...ok, marketCap: 1_999_999_999 },
            5,
            false,
            'market cap < $2B',
        ],
        ['봉 없음', ok, null, false, 'no EOD bars'],
        ['급등락', ok, 20, false, 'max daily change ≥ 20%'],
    ])('%s → 탈락', (_label, profile, change, includeEtf, reason) => {
        expect(visitUsRejection(profile, change, includeEtf)).toBe(reason);
    });

    it('--include-etf면 ETF 통과', () => {
        expect(visitUsRejection({ ...ok, isEtf: true }, 5, true)).toBeNull();
    });
});

describe('visitKrRejection', () => {
    it('상장·시총 1조 이상이면 null', () => {
        expect(visitKrRejection('유한양행', 5_000_000_000_000)).toBeNull();
    });
    it('korean_tickers에 없거나 상장폐지 → 탈락', () => {
        expect(visitKrRejection(undefined, 5_000_000_000_000)).toBe(
            'not listed in korean_tickers'
        );
    });
    it('시총 조회 실패 → 탈락', () => {
        expect(visitKrRejection('유한양행', null)).toBe('no market cap');
    });
    it('1조 미만 → 탈락', () => {
        expect(visitKrRejection('소형주', 999_999_999_999)).toBe(
            'market cap < ₩1조'
        );
    });
});
