import type { KoreanTickerEntry } from '../src/domain/types';

/**
 * 주요 US 종목 한국어 이름 seed 데이터.
 * sync-korean-tickers.ts 스크립트로 Redis에 로드하거나 Redis에서 내보낼 때 사용.
 *
 * 사용법:
 *   npx tsx scripts/sync-korean-tickers.ts seed    # Redis에 업로드
 *   npx tsx scripts/sync-korean-tickers.ts export  # Redis에서 이 파일로 내보내기
 */
export const KOREAN_TICKERS_SEED: readonly KoreanTickerEntry[] = [
    {
        symbol: 'AAPL',
        koreanName: '애플',
        name: 'Apple Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'ABNB',
        koreanName: '에어비앤비',
        name: 'Airbnb Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'ADBE',
        koreanName: '어도비',
        name: 'Adobe Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'AMD',
        koreanName: 'AMD',
        name: 'Advanced Micro Devices Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'AMZN',
        koreanName: '아마존',
        name: 'Amazon.com Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'AVGO',
        koreanName: '브로드컴',
        name: 'Broadcom Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'BAC',
        koreanName: '뱅크오브아메리카',
        name: 'Bank of America Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'BABA',
        koreanName: '알리바바',
        name: 'Alibaba Group Holding Ltd.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'BRK-B',
        koreanName: '버크셔해서웨이',
        name: 'Berkshire Hathaway Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'C',
        koreanName: '씨티그룹',
        name: 'Citigroup Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'CAT',
        koreanName: '캐터필러',
        name: 'Caterpillar Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'COIN',
        koreanName: '코인베이스',
        name: 'Coinbase Global Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'CRM',
        koreanName: '세일즈포스',
        name: 'Salesforce Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'CSCO',
        koreanName: '시스코',
        name: 'Cisco Systems Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'DIS',
        koreanName: '월트디즈니',
        name: 'Walt Disney Co.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'F',
        koreanName: '포드',
        name: 'Ford Motor Co.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'GM',
        koreanName: 'GM',
        name: 'General Motors Co.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'GOOG',
        koreanName: '구글',
        name: 'Alphabet Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'GOOGL',
        koreanName: '알파벳',
        name: 'Alphabet Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'GS',
        koreanName: '골드만삭스',
        name: 'Goldman Sachs Group Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'HD',
        koreanName: '홈디포',
        name: 'Home Depot Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'IBM',
        koreanName: 'IBM',
        name: 'International Business Machines Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'INTC',
        koreanName: '인텔',
        name: 'Intel Corp.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'JNJ',
        koreanName: '존슨앤존슨',
        name: 'Johnson & Johnson',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'JPM',
        koreanName: 'JP모건',
        name: 'JPMorgan Chase & Co.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'KO',
        koreanName: '코카콜라',
        name: 'Coca-Cola Co.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'LLY',
        koreanName: '일라이릴리',
        name: 'Eli Lilly and Co.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'MA',
        koreanName: '마스터카드',
        name: 'Mastercard Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'MCD',
        koreanName: '맥도날드',
        name: "McDonald's Corp.",
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'META',
        koreanName: '메타',
        name: 'Meta Platforms Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'MRK',
        koreanName: '머크',
        name: 'Merck & Co. Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'MSFT',
        koreanName: '마이크로소프트',
        name: 'Microsoft Corp.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'MSTR',
        koreanName: '마이크로스트래티지',
        name: 'MicroStrategy Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'NFLX',
        koreanName: '넷플릭스',
        name: 'Netflix Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'NKE',
        koreanName: '나이키',
        name: 'Nike Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'NVDA',
        koreanName: '엔비디아',
        name: 'NVIDIA Corp.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'ORCL',
        koreanName: '오라클',
        name: 'Oracle Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'PEP',
        koreanName: '펩시코',
        name: 'PepsiCo Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'PFE',
        koreanName: '화이자',
        name: 'Pfizer Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'PG',
        koreanName: 'P&G',
        name: 'Procter & Gamble Co.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'PLTR',
        koreanName: '팔란티어',
        name: 'Palantir Technologies Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'PYPL',
        koreanName: '페이팔',
        name: 'PayPal Holdings Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'QCOM',
        koreanName: '퀄컴',
        name: 'Qualcomm Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'RBLX',
        koreanName: '로블록스',
        name: 'Roblox Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'RIVN',
        koreanName: '리비안',
        name: 'Rivian Automotive Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'SBUX',
        koreanName: '스타벅스',
        name: 'Starbucks Corp.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'SMCI',
        koreanName: '슈퍼마이크로',
        name: 'Super Micro Computer Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'SNAP',
        koreanName: '스냅',
        name: 'Snap Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'SPOT',
        koreanName: '스포티파이',
        name: 'Spotify Technology SA',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'T',
        koreanName: 'AT&T',
        name: 'AT&T Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'TSLA',
        koreanName: '테슬라',
        name: 'Tesla Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'TSM',
        koreanName: 'TSMC',
        name: 'Taiwan Semiconductor Manufacturing Co.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'UBER',
        koreanName: '우버',
        name: 'Uber Technologies Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'UNH',
        koreanName: '유나이티드헬스',
        name: 'UnitedHealth Group Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'V',
        koreanName: '비자',
        name: 'Visa Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'WMT',
        koreanName: '월마트',
        name: 'Walmart Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'X',
        koreanName: 'US스틸',
        name: 'United States Steel Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'XOM',
        koreanName: '엑슨모빌',
        name: 'Exxon Mobil Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
];
