import type { KoreanTickerEntry } from '@/domain/types';

/**
 * 주요 US 종목 한국어 이름 seed 데이터.
 * sync-korean-tickers.ts 스크립트로 Redis에 로드하거나 Redis에서 내보낼 때 사용.
 */
export const KOREAN_TICKERS_SEED: readonly KoreanTickerEntry[] = [
    // ── 개별 종목 ─────────────────────────────────────────────
    {
        symbol: 'AAPL',
        koreanName: '애플',
        name: 'Apple Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'ABBV',
        koreanName: '애브비',
        name: 'AbbVie Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'ABNB',
        koreanName: '에어비앤비',
        name: 'Airbnb Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'ABT',
        koreanName: '애보트',
        name: 'Abbott Laboratories',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'ACHR',
        koreanName: '아처에비에이션',
        name: 'Archer Aviation Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'ACN',
        koreanName: '액센추어',
        name: 'Accenture plc',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'ADBE',
        koreanName: '어도비',
        name: 'Adobe Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'AFRM',
        koreanName: '어펌',
        name: 'Affirm Holdings Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'AI',
        koreanName: 'C3.ai',
        name: 'C3.ai Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'AMAT',
        koreanName: '어플라이드머티리얼즈',
        name: 'Applied Materials Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'AMD',
        koreanName: 'AMD',
        name: 'Advanced Micro Devices Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'AMGN',
        koreanName: '암젠',
        name: 'Amgen Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'AMT',
        koreanName: '아메리칸타워',
        name: 'American Tower Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'AMZN',
        koreanName: '아마존',
        name: 'Amazon.com Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'ARQQ',
        koreanName: '아르킷퀀텀',
        name: 'Arqit Quantum Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'ARM',
        koreanName: 'ARM홀딩스',
        name: 'Arm Holdings plc',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'ASML',
        koreanName: 'ASML',
        name: 'ASML Holding NV',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'ASTS',
        koreanName: 'AST스페이스모바일',
        name: 'AST SpaceMobile Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'AVGO',
        koreanName: '브로드컴',
        name: 'Broadcom Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'AXP',
        koreanName: '아메리칸익스프레스',
        name: 'American Express Co.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'BA',
        koreanName: '보잉',
        name: 'Boeing Co.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'BABA',
        koreanName: '알리바바',
        name: 'Alibaba Group Holding Ltd.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'BAC',
        koreanName: '뱅크오브아메리카',
        name: 'Bank of America Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'BBAI',
        koreanName: '빅베어AI',
        name: 'BigBear.ai Holdings Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'BIDU',
        koreanName: '바이두',
        name: 'Baidu Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'BIIB',
        koreanName: '바이오젠',
        name: 'Biogen Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'BLK',
        koreanName: '블랙록',
        name: 'BlackRock Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'BMY',
        koreanName: '브리스톨마이어스스퀴브',
        name: 'Bristol-Myers Squibb Co.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'BRK-B',
        koreanName: '버크셔해서웨이',
        name: 'Berkshire Hathaway Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'BX',
        koreanName: '블랙스톤',
        name: 'Blackstone Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'C',
        koreanName: '씨티그룹',
        name: 'Citigroup Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'CAT',
        koreanName: '캐터필러',
        name: 'Caterpillar Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'CL',
        koreanName: '콜게이트팜올리브',
        name: 'Colgate-Palmolive Co.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'CMG',
        koreanName: '치폴레',
        name: 'Chipotle Mexican Grill Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'COIN',
        koreanName: '코인베이스',
        name: 'Coinbase Global Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'COP',
        koreanName: '코노코필립스',
        name: 'ConocoPhillips',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'COST',
        koreanName: '코스트코',
        name: 'Costco Wholesale Corp.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'CRM',
        koreanName: '세일즈포스',
        name: 'Salesforce Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'CRWD',
        koreanName: '크라우드스트라이크',
        name: 'CrowdStrike Holdings Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'CSCO',
        koreanName: '시스코',
        name: 'Cisco Systems Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'CVS',
        koreanName: 'CVS헬스',
        name: 'CVS Health Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'CVX',
        koreanName: '셰브론',
        name: 'Chevron Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'D',
        koreanName: '도미니언에너지',
        name: 'Dominion Energy Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'DASH',
        koreanName: '도어대시',
        name: 'DoorDash Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'DDOG',
        koreanName: '데이터독',
        name: 'Datadog Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'DE',
        koreanName: '존디어',
        name: 'Deere & Company',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'DHR',
        koreanName: '다나허',
        name: 'Danaher Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'DIS',
        koreanName: '월트디즈니',
        name: 'Walt Disney Co.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'DUK',
        koreanName: '듀크에너지',
        name: 'Duke Energy Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'ENPH',
        koreanName: '엔페이즈에너지',
        name: 'Enphase Energy Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'F',
        koreanName: '포드',
        name: 'Ford Motor Co.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'FDX',
        koreanName: '페덱스',
        name: 'FedEx Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'FSLR',
        koreanName: '퍼스트솔라',
        name: 'First Solar Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'GE',
        koreanName: 'GE에어로스페이스',
        name: 'GE Aerospace',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'GILD',
        koreanName: '길리어드사이언스',
        name: 'Gilead Sciences Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'GM',
        koreanName: 'GM',
        name: 'General Motors Co.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'GOOG',
        koreanName: '구글',
        name: 'Alphabet Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'GOOGL',
        koreanName: '알파벳',
        name: 'Alphabet Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'GS',
        koreanName: '골드만삭스',
        name: 'Goldman Sachs Group Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'HD',
        koreanName: '홈디포',
        name: 'Home Depot Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'HON',
        koreanName: '하니웰',
        name: 'Honeywell International Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'HOOD',
        koreanName: '로빈후드',
        name: 'Robinhood Markets Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'HSY',
        koreanName: '허쉬',
        name: 'Hershey Co.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'HUM',
        koreanName: '휴마나',
        name: 'Humana Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'HUT',
        koreanName: 'Hut8',
        name: 'Hut 8 Corp.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'IBM',
        koreanName: 'IBM',
        name: 'International Business Machines Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'INTC',
        koreanName: '인텔',
        name: 'Intel Corp.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'INTU',
        koreanName: '인튜이트',
        name: 'Intuit Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'IONQ',
        koreanName: '아이온큐',
        name: 'IonQ Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'ISRG',
        koreanName: '인튜이티브서지컬',
        name: 'Intuitive Surgical Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'JD',
        koreanName: '징둥닷컴',
        name: 'JD.com Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'JNJ',
        koreanName: '존슨앤존슨',
        name: 'Johnson & Johnson',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'JOBY',
        koreanName: '조비에비에이션',
        name: 'Joby Aviation Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'JPM',
        koreanName: 'JP모건',
        name: 'JPMorgan Chase & Co.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'KLAC',
        koreanName: 'KLA',
        name: 'KLA Corp.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'KMB',
        koreanName: '킴벌리클라크',
        name: 'Kimberly-Clark Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'KO',
        koreanName: '코카콜라',
        name: 'Coca-Cola Co.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'KTOS',
        koreanName: '크라토스디펜스',
        name: 'Kratos Defense & Security Solutions Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'LCID',
        koreanName: '루시드그룹',
        name: 'Lucid Group Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'LI',
        koreanName: '리오토',
        name: 'Li Auto Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'LLY',
        koreanName: '일라이릴리',
        name: 'Eli Lilly and Co.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'LMT',
        koreanName: '록히드마틴',
        name: 'Lockheed Martin Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'LOW',
        koreanName: '로우스',
        name: "Lowe's Companies Inc.",
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'LRCX',
        koreanName: '램리서치',
        name: 'Lam Research Corp.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'LULU',
        koreanName: '룰루레몬',
        name: 'Lululemon Athletica Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'LUNR',
        koreanName: '인튜이티브머신스',
        name: 'Intuitive Machines Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'LYFT',
        koreanName: '리프트',
        name: 'Lyft Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'MA',
        koreanName: '마스터카드',
        name: 'Mastercard Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'MARA',
        koreanName: '마라톤디지털',
        name: 'Marathon Digital Holdings Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'MCD',
        koreanName: '맥도날드',
        name: "McDonald's Corp.",
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'MDT',
        koreanName: '메드트로닉',
        name: 'Medtronic plc',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'META',
        koreanName: '메타',
        name: 'Meta Platforms Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'MMM',
        koreanName: '쓰리엠',
        name: '3M Co.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'MO',
        koreanName: '알트리아',
        name: 'Altria Group Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'MRK',
        koreanName: '머크',
        name: 'Merck & Co. Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'MRO',
        koreanName: '마라톤오일',
        name: 'Marathon Oil Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'MRVL',
        koreanName: '마벨테크놀로지',
        name: 'Marvell Technology Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'MS',
        koreanName: '모건스탠리',
        name: 'Morgan Stanley',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'MSFT',
        koreanName: '마이크로소프트',
        name: 'Microsoft Corp.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'MSTR',
        koreanName: '마이크로스트래티지',
        name: 'MicroStrategy Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'MU',
        koreanName: '마이크론테크놀로지',
        name: 'Micron Technology Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'NEE',
        koreanName: '넥스트에라에너지',
        name: 'NextEra Energy Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'NET',
        koreanName: '클라우드플레어',
        name: 'Cloudflare Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'NFLX',
        koreanName: '넷플릭스',
        name: 'Netflix Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'NIO',
        koreanName: '니오',
        name: 'NIO Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'NKE',
        koreanName: '나이키',
        name: 'Nike Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'NOC',
        koreanName: '노스롭그루먼',
        name: 'Northrop Grumman Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'NOW',
        koreanName: '서비스나우',
        name: 'ServiceNow Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'NU',
        koreanName: '누뱅크',
        name: 'Nu Holdings Ltd.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'NVDA',
        koreanName: '엔비디아',
        name: 'NVIDIA Corp.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'O',
        koreanName: '리얼티인컴',
        name: 'Realty Income Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'ON',
        koreanName: '온세미컨덕터',
        name: 'ON Semiconductor Corp.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'ORCL',
        koreanName: '오라클',
        name: 'Oracle Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'OXY',
        koreanName: '옥시덴탈페트롤리엄',
        name: 'Occidental Petroleum Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'PANW',
        koreanName: '팔로알토네트웍스',
        name: 'Palo Alto Networks Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'PDD',
        koreanName: '핀둬둬',
        name: 'PDD Holdings Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'PEP',
        koreanName: '펩시코',
        name: 'PepsiCo Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'PFE',
        koreanName: '화이자',
        name: 'Pfizer Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'PG',
        koreanName: 'P&G',
        name: 'Procter & Gamble Co.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'PINS',
        koreanName: '핀터레스트',
        name: 'Pinterest Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'PLTR',
        koreanName: '팔란티어',
        name: 'Palantir Technologies Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'PLUG',
        koreanName: '플러그파워',
        name: 'Plug Power Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'PM',
        koreanName: '필립모리스',
        name: 'Philip Morris International Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'PNC',
        koreanName: 'PNC파이낸셜',
        name: 'PNC Financial Services Group Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'PYPL',
        koreanName: '페이팔',
        name: 'PayPal Holdings Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'QBTS',
        koreanName: 'D-Wave퀀텀',
        name: 'D-Wave Quantum Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'QCOM',
        koreanName: '퀄컴',
        name: 'Qualcomm Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'QUBT',
        koreanName: '퀀텀컴퓨팅',
        name: 'Quantum Computing Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'RBLX',
        koreanName: '로블록스',
        name: 'Roblox Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'RDDT',
        koreanName: '레딧',
        name: 'Reddit Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'REGN',
        koreanName: '리제네론',
        name: 'Regeneron Pharmaceuticals Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'RGTI',
        koreanName: '리게티컴퓨팅',
        name: 'Rigetti Computing Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'RIVN',
        koreanName: '리비안',
        name: 'Rivian Automotive Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'RKLB',
        koreanName: '로켓랩',
        name: 'Rocket Lab USA Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'ROKU',
        koreanName: '로쿠',
        name: 'Roku Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'RTX',
        koreanName: 'RTX',
        name: 'RTX Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'SBUX',
        koreanName: '스타벅스',
        name: 'Starbucks Corp.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'SCHW',
        koreanName: '찰스슈왑',
        name: 'Charles Schwab Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'SHOP',
        koreanName: '쇼피파이',
        name: 'Shopify Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'SLB',
        koreanName: '슐럼버거',
        name: 'SLB',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'SMCI',
        koreanName: '슈퍼마이크로',
        name: 'Super Micro Computer Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'SNAP',
        koreanName: '스냅',
        name: 'Snap Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'SNOW',
        koreanName: '스노우플레이크',
        name: 'Snowflake Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'SO',
        koreanName: '서던컴퍼니',
        name: 'Southern Company',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'SOFI',
        koreanName: '소파이테크놀로지스',
        name: 'SoFi Technologies Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'SOUN',
        koreanName: '사운드하운드AI',
        name: 'SoundHound AI Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'SPOT',
        koreanName: '스포티파이',
        name: 'Spotify Technology SA',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'SYK',
        koreanName: '스트라이커',
        name: 'Stryker Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'T',
        koreanName: 'AT&T',
        name: 'AT&T Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'TGT',
        koreanName: '타겟',
        name: 'Target Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'TJX',
        koreanName: 'TJX',
        name: 'TJX Companies Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'TMO',
        koreanName: '써모피셔사이언티픽',
        name: 'Thermo Fisher Scientific Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'TMUS',
        koreanName: 'T모바일',
        name: 'T-Mobile US Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'TSLA',
        koreanName: '테슬라',
        name: 'Tesla Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'TSM',
        koreanName: 'TSMC',
        name: 'Taiwan Semiconductor Manufacturing Co.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'TXN',
        koreanName: '텍사스인스트루먼츠',
        name: 'Texas Instruments Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'UBER',
        koreanName: '우버',
        name: 'Uber Technologies Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'UNH',
        koreanName: '유나이티드헬스',
        name: 'UnitedHealth Group Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'UPS',
        koreanName: 'UPS',
        name: 'United Parcel Service Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'USB',
        koreanName: 'US뱅코프',
        name: 'U.S. Bancorp',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'V',
        koreanName: '비자',
        name: 'Visa Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'VRTX',
        koreanName: '버텍스파마슈티컬스',
        name: 'Vertex Pharmaceuticals Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'VZ',
        koreanName: '버라이즌',
        name: 'Verizon Communications Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'WDC',
        koreanName: '웨스턴디지털',
        name: 'Western Digital Corp.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'WFC',
        koreanName: '웰스파고',
        name: 'Wells Fargo & Co.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'WMT',
        koreanName: '월마트',
        name: 'Walmart Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'X',
        koreanName: 'US스틸',
        name: 'United States Steel Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'XPEV',
        koreanName: '샤오펑',
        name: 'XPeng Inc.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'XOM',
        koreanName: '엑슨모빌',
        name: 'Exxon Mobil Corp.',
        exchange: 'NYSE',
        exchangeFullName: 'New York Stock Exchange',
    },
    {
        symbol: 'ZM',
        koreanName: '줌',
        name: 'Zoom Video Communications Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'ZS',
        koreanName: '지스케일러',
        name: 'Zscaler Inc.',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },

    // ── 주요 지수 ETF ──────────────────────────────────────────
    {
        symbol: 'SPY',
        koreanName: 'S&P500 ETF',
        name: 'SPDR S&P 500 ETF Trust',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
    {
        symbol: 'VOO',
        koreanName: '뱅가드 S&P500 ETF',
        name: 'Vanguard S&P 500 ETF',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
    {
        symbol: 'QQQ',
        koreanName: '나스닥100 ETF',
        name: 'Invesco QQQ Trust',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'DIA',
        koreanName: '다우존스 ETF',
        name: 'SPDR Dow Jones Industrial Average ETF Trust',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
    {
        symbol: 'IWM',
        koreanName: '러셀2000 ETF',
        name: 'iShares Russell 2000 ETF',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },

    // ── 레버리지 / 인버스 ETF ─────────────────────────────────
    {
        symbol: 'TQQQ',
        koreanName: '나스닥100 3배 ETF',
        name: 'ProShares UltraPro QQQ',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'SQQQ',
        koreanName: '나스닥100 -3배 ETF',
        name: 'ProShares UltraPro Short QQQ',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'SPXL',
        koreanName: 'S&P500 3배 ETF',
        name: 'Direxion Daily S&P 500 Bull 3X Shares',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
    {
        symbol: 'SPXS',
        koreanName: 'S&P500 -3배 ETF',
        name: 'Direxion Daily S&P 500 Bear 3X Shares',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },

    // ── 반도체 섹터 ETF ────────────────────────────────────────
    {
        symbol: 'SOXX',
        koreanName: '반도체 ETF',
        name: 'iShares Semiconductor ETF',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'SMH',
        koreanName: '반도체 ETF (VanEck)',
        name: 'VanEck Semiconductor ETF',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
    {
        symbol: 'SOXL',
        koreanName: '반도체 3배 ETF',
        name: 'Direxion Daily Semiconductor Bull 3X Shares',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
    {
        symbol: 'SOXS',
        koreanName: '반도체 -3배 ETF',
        name: 'Direxion Daily Semiconductor Bear 3X Shares',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },

    // ── 양자컴퓨팅 섹터 ETF ────────────────────────────────────
    {
        symbol: 'QTUM',
        koreanName: '양자컴퓨팅 ETF',
        name: 'Defiance Quantum ETF',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },

    // ── 보안 / 사이버보안 섹터 ETF ─────────────────────────────
    {
        symbol: 'CIBR',
        koreanName: '사이버보안 ETF',
        name: 'First Trust NASDAQ Cybersecurity ETF',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'HACK',
        koreanName: '사이버보안 ETF (HACK)',
        name: 'ETFMG Prime Cyber Security ETF',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
    {
        symbol: 'BUG',
        koreanName: '사이버보안 ETF (글로벌X)',
        name: 'Global X Cybersecurity ETF',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },

    // ── 기술 섹터 ETF ──────────────────────────────────────────
    {
        symbol: 'XLK',
        koreanName: '기술 섹터 ETF',
        name: 'Technology Select Sector SPDR Fund',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
    {
        symbol: 'VGT',
        koreanName: '뱅가드 IT ETF',
        name: 'Vanguard Information Technology ETF',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },

    // ── 금융 섹터 ETF ──────────────────────────────────────────
    {
        symbol: 'XLF',
        koreanName: '금융 섹터 ETF',
        name: 'Financial Select Sector SPDR Fund',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
    {
        symbol: 'KRE',
        koreanName: '지역은행 ETF',
        name: 'SPDR S&P Regional Banking ETF',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },

    // ── 헬스케어 / 바이오테크 섹터 ETF ────────────────────────
    {
        symbol: 'XLV',
        koreanName: '헬스케어 섹터 ETF',
        name: 'Health Care Select Sector SPDR Fund',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
    {
        symbol: 'XBI',
        koreanName: '바이오테크 ETF',
        name: 'SPDR S&P Biotech ETF',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
    {
        symbol: 'IBB',
        koreanName: '바이오테크 ETF (iShares)',
        name: 'iShares Biotechnology ETF',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },

    // ── 에너지 섹터 ETF ────────────────────────────────────────
    {
        symbol: 'XLE',
        koreanName: '에너지 섹터 ETF',
        name: 'Energy Select Sector SPDR Fund',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
    {
        symbol: 'USO',
        koreanName: '원유 ETF',
        name: 'United States Oil Fund',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },

    // ── 경기방어주 / 필수소비재 섹터 ETF ──────────────────────
    {
        symbol: 'XLP',
        koreanName: '필수소비재 섹터 ETF',
        name: 'Consumer Staples Select Sector SPDR Fund',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
    {
        symbol: 'XLU',
        koreanName: '유틸리티 섹터 ETF',
        name: 'Utilities Select Sector SPDR Fund',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },

    // ── 배당 섹터 ETF ──────────────────────────────────────────
    {
        symbol: 'SCHD',
        koreanName: '배당 ETF (슈왑)',
        name: 'Schwab US Dividend Equity ETF',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
    {
        symbol: 'VYM',
        koreanName: '고배당 ETF (뱅가드)',
        name: 'Vanguard High Dividend Yield ETF',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
    {
        symbol: 'DVY',
        koreanName: '배당 ETF (iShares)',
        name: 'iShares Select Dividend ETF',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },

    // ── 국채 / 채권 ETF ────────────────────────────────────────
    {
        symbol: 'TLT',
        koreanName: '미국 장기국채 ETF',
        name: 'iShares 20+ Year Treasury Bond ETF',
        exchange: 'NASDAQ',
        exchangeFullName: 'NASDAQ Global Select',
    },
    {
        symbol: 'TMF',
        koreanName: '미국 장기국채 3배 ETF',
        name: 'Direxion Daily 20+ Year Treasury Bull 3X Shares',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
    {
        symbol: 'TBT',
        koreanName: '미국 장기국채 -2배 ETF',
        name: 'ProShares UltraShort 20+ Year Treasury',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },

    // ── 혁신 / 성장 ETF ────────────────────────────────────────
    {
        symbol: 'ARKK',
        koreanName: 'ARK 이노베이션 ETF',
        name: 'ARK Innovation ETF',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
    {
        symbol: 'ARKG',
        koreanName: 'ARK 유전체혁명 ETF',
        name: 'ARK Genomic Revolution ETF',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },

    // ── 금 / 원자재 ETF ────────────────────────────────────────
    {
        symbol: 'GLD',
        koreanName: '금 ETF',
        name: 'SPDR Gold Shares',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
    {
        symbol: 'GDX',
        koreanName: '금광주 ETF',
        name: 'VanEck Gold Miners ETF',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
    {
        symbol: 'SLV',
        koreanName: '은 ETF',
        name: 'iShares Silver Trust',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },

    // ── 방산 / 항공우주 섹터 ETF ───────────────────────────────
    {
        symbol: 'XAR',
        koreanName: '항공우주방산 ETF',
        name: 'SPDR S&P Aerospace & Defense ETF',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
    {
        symbol: 'ITA',
        koreanName: '방산 ETF (iShares)',
        name: 'iShares U.S. Aerospace & Defense ETF',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },

    // ── 산업 / 소재 / 부동산 / 통신 / 경기민감소비 섹터 ETF ───
    {
        symbol: 'XLI',
        koreanName: '산업 섹터 ETF',
        name: 'Industrial Select Sector SPDR Fund',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
    {
        symbol: 'XLB',
        koreanName: '소재 섹터 ETF',
        name: 'Materials Select Sector SPDR Fund',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
    {
        symbol: 'XLRE',
        koreanName: '부동산 섹터 ETF',
        name: 'Real Estate Select Sector SPDR Fund',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
    {
        symbol: 'VNQ',
        koreanName: '부동산 ETF (뱅가드)',
        name: 'Vanguard Real Estate ETF',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
    {
        symbol: 'XLC',
        koreanName: '통신서비스 섹터 ETF',
        name: 'Communication Services Select Sector SPDR Fund',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
    {
        symbol: 'XLY',
        koreanName: '경기민감소비 섹터 ETF',
        name: 'Consumer Discretionary Select Sector SPDR Fund',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },

    // ── 중국 ETF ───────────────────────────────────────────────
    {
        symbol: 'FXI',
        koreanName: '중국 대형주 ETF',
        name: 'iShares China Large-Cap ETF',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
    {
        symbol: 'KWEB',
        koreanName: '중국 인터넷 ETF',
        name: 'KraneShares CSI China Internet ETF',
        exchange: 'AMEX',
        exchangeFullName: 'NYSE ARCA',
    },
];
